---
version: "3"
services:
    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - /Users:/Users
            - /Users/jiacheng3/Documents/Website/Configuration/Nginx/nginx.conf:/etc/nginx/nginx.conf
            - /Users/jiacheng3/Documents/Website/Configuration/Nginx/conf.d:/etc/nginx/conf.d

    redis:
        image: redis:latest
        ports:
            - 6379:6379

    memcached:
        image: memcached:latest
        ports:
            - 11211:11211
