---
version: "3"
services:
    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./config_example/nginx.conf:/etc/nginx/nginx.conf
            - ./config_example/conf.d:/etc/nginx/conf.d

    redis:
        image: redis:latest
        ports:
            - 6379:6379

    memcached:
        image: memcached:latest
        ports:
            - 11211:11211
    mongo:
        image: mongo:latest
        ports:
            - 27017:27017
